server:
  port: 8080
  servlet:
    session:
      timeout: 60
medical:
  jwt:
    user-secret-key: NWcgkfO+ZfZuMOL6pud9wohIiXEooZ1wDU95qR30mEE=
    user-ttl: 7200000
    user-token-name: Authorization
spring:
  banner:
    charset: UTF-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/medical?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

system:
  peers: 192.168.153.132:20200
  groupId: 1
  certPath: conf,config,src/main/resources/conf,src/main/resources/config
  hexPrivateKey: aa17533ec096f0fa56bb3140e66b75c705f295137279317e55c6dd842277e145
  contract:
    medicalRecordManagementAddress: 0x748486f07be8413fe3b2595c8c467390897f14b1
